"""init2

Revision ID: 026affbb8233
Revises: 3278b2267379
Create Date: 2024-09-18 14:10:27.749049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026affbb8233'
down_revision: Union[str, None] = '3278b2267379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('name', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('track_id', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('file_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tracks', ['track_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='unique')
    op.drop_column('tracks', 'file_path')
    op.drop_column('tracks', 'track_id')
    op.drop_column('tracks', 'name')
    # ### end Alembic commands ###
